"""empty message

Revision ID: 27e0547c62b4
Revises: e67b0530cacf
Create Date: 2021-03-24 02:22:44.258407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e0547c62b4'
down_revision = 'e67b0530cacf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('propertyDesc', sa.String(length=160), nullable=True),
    sa.Column('NoOfBedrooms', sa.String(length=10), nullable=True),
    sa.Column('NoOfBathrooms', sa.String(length=10), nullable=True),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('propertyType', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('photo', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('properties')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('propertyDesc', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('NoOfBedrooms', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('NoOfBathrooms', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('propertyType', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_table('property_model')
    # ### end Alembic commands ###
