"""empty message

Revision ID: d414843d4913
Revises: 2ed30baac322
Create Date: 2021-03-22 01:17:43.414692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd414843d4913'
down_revision = '2ed30baac322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('propertyId', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('properties', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('properties', 'propertyId')
    # ### end Alembic commands ###
