"""empty message

Revision ID: e67b0530cacf
Revises: d414843d4913
Create Date: 2021-03-24 02:01:10.003732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67b0530cacf'
down_revision = 'd414843d4913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('properties', 'propertyId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('propertyId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('properties', 'id')
    # ### end Alembic commands ###
